---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  # pre_tasks:
  # - name: "Setting hostname"
  #   shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common

- name: "Deploy gocd"
  gather_facts: true
  hosts: vg-compute-06   
  become: yes
  roles:
    - gocd 

